apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-0-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.3
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
          - $custom/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/sofusalbertsen/argocd-katas3'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/sofusalbertsen/argocd-katas3'
      targetRevision: main
      ref: custom
