apiVersion: v1
data:
  token: Z2l0aHViX3BhdF8xMUFCRExFWEkwVzVPdGtmY1FtcWpYX2NZT2lUSGtmOTU5MjdEV082Qk9DTlBxTUh5OEFXeU8zbGxKeHhKSFE0UlFTREpQNldOTldyeUYzVWI0
kind: Secret
metadata:
  namespace: argocd
  creationTimestamp: null
  name: student-0-gh
